[tool.black]
line-length = 80
target-version = ['py311']

[tool.ruff]
line-length = 80
target-version = 'py311'
builtins = ['custom_target', 'self', 'subpackage']

[tool.ruff.lint]
select = [
    'E',
    'F',
    'RUF',
    'UP',
    'W',
]
ignore = [
    # black compat
    'E203',
    # long source lines
    'E501',
    # unused unpack sequences
    'F841',
    # maybe later
    'RUF005',
    # allow redundant open(, 'r')
    'UP015',
    # we check this intentionally
    'UP036',
]
