name: Lint tree and check format

on:
  push:
    branches:
      - master
    paths:
      - 'main/**'
      - 'contrib/**'
      - 'user/**'
      - 'src/**'

  pull_request:
    branches:
      - master
    paths:
      - 'main/**'
      - 'contrib/**'
      - 'user/**'
      - 'src/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PYTHONUNBUFFERED: 1

jobs:
  lint:
    name: Lint tree and check format
    runs-on: ubuntu-latest
    steps:
      - name: Install apt dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends python3-pip ca-certificates python3.11 openssl git bubblewrap wget

      - name: Install ruff
        run: sudo pip3 install ruff

      - name: Checkout
        uses: classabbyamp/treeless-checkout-action@v1

      - name: Set up cbuild configuration
        run: sh .ci/setup-cbuild.sh

      - name: Run checks and lints
        run: sh .ci/lint.sh
